import "server-only";

import {
  GuardianSecurityError,
  type GuardianSecurityRequest,
  type GuardianSecuritySuccess,
} from "../guardian-security/analysis-types";

import type { GuardianLlmMode } from "./config";
import type { GuardianLlmProvider } from "./provider";
import { runGuardianLlmEnhancement } from "./runner";
import {
  type GuardianCandidateOnlyAnalysisSuccess,
  type GuardianHybridAnalysisOutcome,
  toPublicLlmEnhancement,
} from "./hybrid-analysis-types";
import { guardianSecuritySuccessToVerifiedFindings } from "./verified-finding-adapter";

export type RunDeterministicGuardianAnalysis = (
  request: GuardianSecurityRequest,
) => Promise<GuardianSecuritySuccess>;

export interface RunHybridGuardianAnalysisOptions {
  readonly request: GuardianSecurityRequest;
  readonly mode: GuardianLlmMode;
  readonly provider?: GuardianLlmProvider;
  readonly runDeterministic: RunDeterministicGuardianAnalysis;
  readonly now?: () => Date;
}

function llmRequestForSample(
  request: Extract<GuardianSecurityRequest, { mode: "sample" }>,
  verifiedFindings: ReturnType<
    typeof guardianSecuritySuccessToVerifiedFindings
  >,
) {
  return {
    schemaVersion: "guardian-llm-request-v1",
    verifiedFindings,
    untrustedSources: {
      vulnerableSource: request.sample.vulnerableSource,
      ...(request.sample.attackSource !== undefined
        ? { attackSource: request.sample.attackSource }
        : {}),
      ...(request.sample.fixedSource !== undefined
        ? { fixedSource: request.sample.fixedSource }
        : {}),
    },
  } as const;
}

function candidateOnlyResponse(
  displayName: string,
  response: Parameters<typeof toPublicLlmEnhancement>[0],
  analyzedAt: string,
): GuardianCandidateOnlyAnalysisSuccess {
  return {
    ok: true,
    schemaVersion: "guardian-security-candidate-analysis-v1",
    analyzedAt,
    agent: {
      mode: "hybrid-llm-candidate",
      externalModelConnected: true,
    },
    inputMode: "sample",
    case: {
      caseId: "user-sample",
      displayName,
      provenance: "user-provided-unverified",
    },
    deterministic: null,
    llmEnhancement: toPublicLlmEnhancement(response),
    submission: {
      allowed: false,
      reason: "LLM_CANDIDATE_REQUIRES_SIGNED_DRAFT_OR_VERIFICATION",
    },
    review: {
      requiresHumanApproval: true,
      publishAllowed: false,
    },
    limitations: [
      "Candidate findings were generated by an external model and are not deterministically verified.",
      "No authoritative realm, element classification, severity, confidence, Bestiary draft, or Quest draft is produced.",
      "Contribution submission is disabled until a signed draft or deterministic verification flow is implemented.",
      "Human security review is required before publication.",
    ],
  };
}

export async function runHybridGuardianAnalysis(
  options: RunHybridGuardianAnalysisOptions,
): Promise<GuardianHybridAnalysisOutcome> {
  if (options.request.mode === "builtin") {
    const deterministicResult = await options.runDeterministic(options.request);
    return {
      kind: "deterministic",
      response: deterministicResult,
      deterministicResult,
    };
  }

  let deterministicResult: GuardianSecuritySuccess;
  try {
    deterministicResult = await options.runDeterministic(options.request);
  } catch (error: unknown) {
    if (
      !(error instanceof GuardianSecurityError) ||
      error.code !== "UNSUPPORTED_VULNERABILITY"
    ) {
      throw error;
    }

    const llmResult = await runGuardianLlmEnhancement({
      mode: options.mode,
      input: llmRequestForSample(options.request, []),
      provider: options.provider,
    });

    if (llmResult.status !== "enhanced") {
      throw error;
    }

    return {
      kind: "candidate-only",
      response: candidateOnlyResponse(
        options.request.sample.name,
        llmResult.response,
        (options.now ?? (() => new Date()))().toISOString(),
      ),
      deterministicResult: null,
    };
  }

  const llmResult = await runGuardianLlmEnhancement({
    mode: options.mode,
    input: llmRequestForSample(
      options.request,
      guardianSecuritySuccessToVerifiedFindings(deterministicResult),
    ),
    provider: options.provider,
  });

  if (llmResult.status !== "enhanced") {
    return {
      kind: "deterministic",
      response: deterministicResult,
      deterministicResult,
    };
  }

  return {
    kind: "deterministic",
    response: {
      ...deterministicResult,
      llmEnhancement: toPublicLlmEnhancement(llmResult.response),
    },
    deterministicResult,
  };
}
